---
- name: Install tmux
  homebrew:
   name: tmux
   state: present
   update_homebrew: yes
  tags:
   - dev-prod
- name: Install stow
  homebrew:
   name: stow
   state: present
  tags:
   - dev-prod
