- name: Install Docker
  apt:
    name: docker.io
    state: present
  tags:
    - docker

- name: Start the Docker service
  service:
    name: docker
    state: started
  tags:
    - docker

- name: Enable Docker service at boot
  service:
    name: docker
    enabled: yes
  tags:
    - docker
